In [462]:
import pandas as pd
import matplotlib
import datetime

file_path = '/home/mint/Downloads/top_dest_output.csv'

df = pd.read_csv(file_path, names=['MMSI', 'Start_cell', 'End_cell', 'Start_time', 'End_time'])
df.head()

        MMSI Start_cell  End_cell           Start_time             End_time
0  412430638   C1513136  C1513126  2016-12-02 22:15:11  2016-12-08 23:30:44
1  412430621   C1513136  C1513126  2016-07-23 17:17:03  2016-08-01 11:33:32
2  412407050   C1513136  C1513126  2016-03-31 09:31:48  2016-04-01 10:25:23
3  412401208   C1513136  C1513126  2016-07-28 15:43:49  2016-08-10 19:47:41
4  412379010   C1513136  C1513126  2016-08-14 03:39:58  2016-08-16 07:40:41

In [495]:
df.describe('')

               MMSI          journey_length  epoch_journey_length
count  3.073818e+06                 3073818          3.073818e+06
mean   3.928629e+08  2 days 05:57:25.963255          1.942460e+05
std    1.222949e+08  9 days 07:23:30.946397          8.042109e+05
min    1.101198e+06         0 days 00:00:01          1.000000e+00
50%    4.127519e+08         0 days 08:12:22          2.954200e+04
max    1.000000e+09       348 days 23:11:54          3.015071e+07

In [496]:
route_groupedDF = df[["Start_cell", "End_cell", "MMSI"]].groupby(["Start_cell", "End_cell"]).agg('count')

In [497]:
route_groupedDF = route_groupedDF.sort_values('MMSI', ascending=False)
dfroute_grouped = route_groupedDF.rename(columns={'MMSI':'Count'})

In [498]:
dfroute_grouped

                     Count
Start_cell End_cell
C1512111   C1513178  24508
C1513127   C1513136  22261
C1513136   C1513127  17844
C1513126   C1513136  16278
C1511661   C1511421  15003
C1513136   C1513126  14597
C1511421   C1511661  14398
JP54M56O   JP54LHLJ  12527
C1513179   C1513136  11713
SE5CI5E0   SE5EHZTR  11359
C1513121   C1513136  11233
C1513178   C1511421  10945
C1514479   C1515379  10841
C1513949   C1513735  10799
C1513178   C1511981  10711
C1511781   C1511941  10284
C1513136   C1513121  10264
C1511421   C1512111   9411
C1514351   C1514479   9401
C1513735   C1513949   9299
C1513631   C1513519   9299
C1514479   C1514351   9275
SE5EHZTR   SE5CI5E0   9070
C1513519   C1513631   9024
JP54MEVF   JP54M56O   8435
C1515379   C1514479   8409
JP54LHLJ   JP54M56O   8316
C1513136   C1513179   8310
C1513126   C1513179   8299
RU5NTKK9   RU5NTKO0   8097
...                    ...
RU5NDJT1   RU5NTKK9    202
KR5F2K43   KR5G3E21    202
GB50801G   GB50801E    202
IT500099   IT500084    202
IT500311   IT500096    202
IN52075R   SG5C4039    201
ES504126   GB502812    201
C1512577   C1512339    201
GB502812   ES504126    201
C1515322   C1515111    201
C1515456   C1516341    201
EG5EGR11   GB55502B    201
JP551OAM   C1513179    201
IT500311   IT500055    201
US5DE10M   US5VA11M    201
SE5DI7L8   DE516200    201
C1511951   C1513178    201
C1513179   JP551OAM    201
TR52921A   GB52282C    201
US5GA13M   US5SC18M    201
EE50781D   SE5EHZTR    201
C1513126   CN584234    201
US5MI71M   US5MI78M    201
DE516200   SE5DI7L8    201
US5WA04M   JP54OJBH    201
GB52268B   GB52253A    201
TR501311   TR52921A    201
C1514249   C1513399    201
C1513661   C1513989    201
C1513319   C1511961    201

[4142 rows x 1 columns]

In [499]:
df['Start_time'] = pd.to_datetime(df['Start_time'])
df['End_time'] = pd.to_datetime(df['End_time'])
df['End_time']-df['Start_time']
df['journey_length'] = df['End_time']-df['Start_time']

In [500]:
df.sort_values('journey_length', ascending=False).head()

,MMSI,Start_cell,End_cell,Start_time,End_time,journey_length,epoch_journey_length
1543994,413986317,C1513126,C1513136,2016-01-07 03:53:06,2016-12-21 03:05:00,348 days 23:11:54,30150714.0
1200228,413990688,C1513127,C1515456,2016-01-12 14:22:03,2016-12-17 06:24:57,339 days 16:02:54,29347374.0
14625,412352670,C1513179,C1513136,2016-01-17 22:01:58,2016-12-20 16:11:47,337 days 18:09:49,29182189.0
2155873,259293820,NO5E1512,NO5E1514,2016-01-11 13:42:30,2016-12-14 07:49:30,337 days 18:07:00,29182020.0
1896124,701067024,AR530010,UY500041,2016-01-29 14:03:44,2016-12-29 14:06:57,335 days 00:03:13,28944193.0

In [471]:
df ['epoch_journey_length'] = df.journey_length.astype('timedelta64[s]')

In [491]:
dflong_route = df[df.epoch_journey_length > 86400]
dflong_route.sort_values('epoch_journey_length', ascending=False)

,MMSI,Start_cell,End_cell,Start_time,End_time,journey_length,epoch_journey_length
1543994,413986317,C1513126,C1513136,2016-01-07 03:53:06,2016-12-21 03:05:00,348 days 23:11:54,30150714.0
1200228,413990688,C1513127,C1515456,2016-01-12 14:22:03,2016-12-17 06:24:57,339 days 16:02:54,29347374.0
14625,412352670,C1513179,C1513136,2016-01-17 22:01:58,2016-12-20 16:11:47,337 days 18:09:49,29182189.0
2155873,259293820,NO5E1512,NO5E1514,2016-01-11 13:42:30,2016-12-14 07:49:30,337 days 18:07:00,29182020.0
1896124,701067024,AR530010,UY500041,2016-01-29 14:03:44,2016-12-29 14:06:57,335 days 00:03:13,28944193.0
793632,413787201,C1513136,C1513127,2016-01-22 00:40:57,2016-12-21 22:45:18,334 days 22:04:21,28937061.0
441425,413976955,C1515449,C1513131,2016-01-11 22:18:44,2016-12-10 11:35:16,333 days 13:16:32,28818992.0
2082699,413803443,C1513127,C1513332,2016-01-07 02:32:00,2016-12-05 03:39:48,333 days 01:07:48,28775268.0
1237478,538005953,C1513519,SG5C4043,2016-01-08 01:12:21,2016-12-04 22:11:47,331 days 20:59:26,28673966.0
765644,413828469,C1513127,C1513136,2016-01-14 20:47:02,2016-12-09 10:32:27,329 days 13:45:25,28475125.0
2807394,770576258,UY500031,UY500041,2016-01-01 14:34:45,2016-11-24 21:58:46,328 days 07:24:01,28365841.0
761868,413951087,C1513127,C1513136,2016-01-20 15:23:09,2016-12-12 01:44:25,326 days 10:21:16,28203676.0
33849,413806322,C1513121,C1513136,2016-01-21 17:44:50,2016-12-09 11:36:21,322 days 17:51:31,27885091.0
17294,413955273,C1513179,C1513136,2016-01-02 08:58:47,2016-11-20 02:37:30,322 days 17:38:43,27884323.0
2283178,412205665,C1511339,C1512171,2016-01-27 23:50:11,2016-12-15 04:28:36,322 days 04:38:25,27837505.0
729489,412350550,C1513126,C1513359,2016-01-28 16:45:31,2016-12-15 02:22:49,321 days 09:37:18,27769038.0
913770,445192000,C1511381,C1511951,2016-01-16 09:45:33,2016-12-01 19:38:11,320 days 09:52:38,27683558.0
1327924,412437429,C1513571,C1513949,2016-01-07 07:36:10,2016-11-22 06:43:01,319 days 23:06:51,27644811.0
50779,413801608,C1513179,C1513127,2016-02-10 15:54:49,2016-12-26 06:55:22,319 days 15:00:33,27615633.0
1551351,413816987,C1513126,C1513136,2016-01-19 20:08:43,2016-12-02 09:21:51,317 days 13:13:08,27436388.0
1756007,413973429,C1515451,C1515449,2016-01-26 14:37:32,2016-12-09 02:02:13,317 days 11:24:41,27429881.0
1550442,413823187,C1513126,C1513136,2016-01-26 11:51:25,2016-12-08 18:39:33,317 days 06:48:08,27413288.0
1334056,508120064,C1513379,C1512581,2016-01-21 05:49:33,2016-12-03 10:17:59,317 days 04:28:26,27404906.0
2792291,412302697,C1512581,C1512641,2016-01-05 14:10:20,2016-11-17 11:50:59,316 days 21:40:39,27380439.0
885160,413975838,C1513127,C1513179,2016-01-07 07:40:38,2016-11-18 04:32:04,315 days 20:51:26,27291086.0
2025223,413330230,C1511941,C1511862,2016-02-19 15:27:31,2016-12-28 01:08:23,312 days 09:40:52,26991652.0
1554,413976933,C1513136,C1513126,2016-02-08 12:03:13,2016-12-16 19:52:32,312 days 07:49:19,26984959.0
380024,525002083,ID500084,ID5091R1,2016-02-05 03:43:21,2016-12-13 07:23:48,312 days 03:40:27,26970027.0
880190,413794443,C1513179,C1513126,2016-01-08 02:41:25,2016-11-15 02:47:04,312 days 00:05:39,26957139.0
2237463,413235000,KR5G3E24,C1513399,2016-01-30 07:55:55,2016-12-06 20:51:41,311 days 12:55:46,26916946.0
...,...,...,...,...,...,...,...
3016383,212085000,BE5ANTWN,DE521420,2016-04-05 18:29:04,2016-04-06 18:29:09,1 days 00:00:05,86405.0
2517294,248078000,NL500207,DE521420,2016-10-26 14:55:28,2016-10-27 14:55:33,1 days 00:00:05,86405.0
670416,538005919,TR52922A,TR502151,2016-04-29 17:48:17,2016-04-30 17:48:22,1 days 00:00:05,86405.0
1374443,256761000,C1512711,C1513178,2016-12-27 13:29:00,2016-12-28 13:29:05,1 days 00:00:05,86405.0
1077507,219437000,NL500114,SE5DI7L8,2016-09-13 14:15:22,2016-09-14 14:15:26,1 days 00:00:04,86404.0
332572,211697640,SE5EI21S,SE5DI5DU,2016-06-27 14:59:29,2016-06-28 14:59:33,1 days 00:00:04,86404.0
3048513,230663000,PL5SWINO,SE5CI5E0,2016-12-19 17:04:44,2016-12-20 17:04:48,1 days 00:00:04,86404.0
3047290,247320400,ES504811,IT500311,2016-02-18 20:10:34,2016-02-19 20:10:38,1 days 00:00:04,86404.0
255846,413356760,C1515799,C1515449,2016-12-25 22:58:57,2016-12-26 22:59:01,1 days 00:00:04,86404.0
1387287,247349300,IT500255,IT500055,2016-04-11 22:14:11,2016-04-12 22:14:15,1 days 00:00:04,86404.0
602218,636015525,PT526308,FR574330,2016-06-20 23:48:03,2016-06-21 23:48:07,1 days 00:00:04,86404.0
1515985,353289000,BR501821,BR501841,2016-04-03 11:48:20,2016-04-04 11:48:24,1 days 00:00:04,86404.0
2135396,564066000,PT528514,FR574330,2016-11-24 12:18:41,2016-11-25 12:18:44,1 days 00:00:03,86403.0
848535,413789375,C1513136,C1513121,2016-02-27 23:07:42,2016-02-28 23:07:45,1 days 00:00:03,86403.0
1655013,412355490,C1513519,C1513949,2016-06-10 16:34:01,2016-06-11 16:34:04,1 days 00:00:03,86403.0
548534,214182521,TR502929,TR52141A,2016-05-19 19:48:34,2016-05-20 19:48:37,1 days 00:00:03,86403.0
434183,413460810,C1515819,C1516791,2016-08-29 15:01:29,2016-08-30 15:01:32,1 days 00:00:03,86403.0
761772,413952228,C1513127,C1513136,2016-07-29 23:58:01,2016-07-30 23:58:03,1 days 00:00:02,86402.0
255687,413424050,C1515799,C1515449,2016-04-05 13:07:49,2016-04-06 13:07:51,1 days 00:00:02,86402.0
2276074,244660599,NL50124C,BE5KGETE,2016-11-01 17:42:16,2016-11-02 17:42:18,1 days 00:00:02,86402.0
2410841,412378940,C1513949,C1513519,2016-03-01 02:16:52,2016-03-02 02:16:54,1 days 00:00:02,86402.0
2310346,538006717,GB54232A,GB500666,2016-06-17 13:27:49,2016-06-18 13:27:51,1 days 00:00:02,86402.0
1208584,636015667,AU5193P0,AU5144P0,2016-03-11 14:56:16,2016-03-12 14:56:18,1 days 00:00:02,86402.0
2916149,413414940,C1513431,C1513179,2016-12-20 07:45:10,2016-12-21 07:45:12,1 days 00:00:02,86402.0
1018787,249570000,DE521420,NL500207,2016-07-07 21:38:12,2016-07-08 21:38:14,1 days 00:00:02,86402.0
2426926,413902509,C1515456,C1515449,2016-12-19 08:23:12,2016-12-20 08:23:14,1 days 00:00:02,86402.0
1655107,412330760,C1513519,C1513949,2016-04-07 01:04:49,2016-04-08 01:04:51,1 days 00:00:02,86402.0
697133,419000619,IN52101A,IN52056P,2016-04-24 13:02:09,2016-04-25 13:02:10,1 days 00:00:01,86401.0
2776217,636013237,C1513178,JP54N2FM,2016-12-29 10:29:00,2016-12-30 10:29:01,1 days 00:00:01,86401.0
156305,413986577,C1513179,C1515456,2016-01-11 16:18:52,2016-01-12 16:18:53,1 days 00:00:01,86401.0

In [492]:
dflong_route

,MMSI,Start_cell,End_cell,Start_time,End_time,journey_length,epoch_journey_length
0,412430638,C1513136,C1513126,2016-12-02 22:15:11,2016-12-08 23:30:44,6 days 01:15:33,522933.0
1,412430621,C1513136,C1513126,2016-07-23 17:17:03,2016-08-01 11:33:32,8 days 18:16:29,756989.0
2,412407050,C1513136,C1513126,2016-03-31 09:31:48,2016-04-01 10:25:23,1 days 00:53:35,89615.0
3,412401208,C1513136,C1513126,2016-07-28 15:43:49,2016-08-10 19:47:41,13 days 04:03:52,1137832.0
4,412379010,C1513136,C1513126,2016-08-14 03:39:58,2016-08-16 07:40:41,2 days 04:00:43,187243.0
5,412379010,C1513136,C1513126,2016-04-26 09:56:32,2016-04-28 03:47:14,1 days 17:50:42,150642.0
6,412375238,C1513136,C1513126,2016-08-10 01:39:57,2016-09-16 14:14:46,37 days 12:34:49,3242089.0
7,412359590,C1513136,C1513126,2016-12-10 18:23:17,2016-12-12 00:43:11,1 days 06:19:54,109194.0
11,412351350,C1513136,C1513126,2016-08-21 02:08:23,2016-08-24 02:28:06,3 days 00:19:43,260383.0
12,412109230,C1513136,C1513126,2016-03-27 02:41:00,2016-03-31 08:43:50,4 days 06:02:50,367370.0
15,411502599,C1513136,C1513126,2016-10-13 14:33:13,2016-10-27 07:49:36,13 days 17:16:23,1185383.0
16,411174914,C1513136,C1513126,2016-07-01 00:39:04,2016-07-06 16:31:05,5 days 15:52:01,489121.0
17,411044024,C1513136,C1513126,2016-10-24 00:51:38,2016-10-26 23:16:45,2 days 22:25:07,253507.0
20,411043973,C1513136,C1513126,2016-03-09 09:03:15,2016-03-10 16:05:53,1 days 07:02:38,111758.0
21,411041849,C1513136,C1513126,2016-09-13 01:42:31,2016-09-26 06:57:39,13 days 05:15:08,1142108.0
23,411041798,C1513136,C1513126,2016-04-27 12:23:21,2016-05-02 01:57:43,4 days 13:34:22,394462.0
24,410000008,C1513136,C1513126,2016-11-20 05:11:32,2016-11-24 17:50:36,4 days 12:39:04,391144.0
28,409566265,C1513136,C1513126,2016-09-13 09:30:12,2016-09-26 06:57:09,12 days 21:26:57,1114017.0
29,409566265,C1513136,C1513126,2016-07-30 17:28:44,2016-07-31 21:10:29,1 days 03:41:45,99705.0
30,391335783,C1513136,C1513126,2016-03-25 20:38:11,2016-04-12 11:27:40,17 days 14:49:29,1522169.0
31,340475747,C1513136,C1513126,2016-05-23 08:46:59,2016-06-16 05:51:53,23 days 21:04:54,2063094.0
32,340475747,C1513136,C1513126,2016-04-15 20:17:00,2016-05-01 17:05:40,15 days 20:48:40,1370920.0
33,340475731,C1513136,C1513126,2016-04-04 13:34:11,2016-06-16 17:38:56,73 days 04:04:45,6321885.0
34,340475723,C1513136,C1513126,2016-01-23 07:45:38,2016-02-14 04:19:43,21 days 20:34:05,1888445.0
35,340475719,C1513136,C1513126,2016-03-18 18:54:43,2016-03-25 21:35:20,7 days 02:40:37,614437.0
36,340475699,C1513136,C1513126,2016-03-11 19:58:49,2016-03-18 00:12:35,6 days 04:13:46,533626.0
43,289688944,C1513136,C1513126,2016-03-24 02:32:28,2016-03-31 01:08:13,6 days 22:35:45,599745.0
44,272840511,C1513136,C1513126,2016-05-29 15:10:41,2016-08-08 00:51:54,70 days 09:41:13,6082873.0
54,232168342,C1513136,C1513126,2016-11-24 02:12:47,2016-11-28 03:28:51,4 days 01:16:04,350164.0
59,232168342,C1513136,C1513126,2016-10-20 18:19:24,2016-10-27 00:53:31,6 days 06:34:07,542047.0
...,...,...,...,...,...,...,...
3073773,413972186,C1513126,CN584234,2016-03-23 08:48:12,2016-05-01 02:15:19,38 days 17:27:07,3346027.0
3073774,413972182,C1513126,CN584234,2016-01-19 01:49:57,2016-05-24 00:04:22,125 days 22:14:25,10880065.0
3073775,413972179,C1513126,CN584234,2016-07-02 04:03:43,2016-07-10 17:40:27,8 days 13:36:44,740204.0
3073776,413972179,C1513126,CN584234,2016-01-22 03:45:27,2016-03-09 09:52:12,47 days 06:06:45,4082805.0
3073777,413972169,C1513126,CN584234,2016-12-16 02:22:14,2016-12-20 06:40:49,4 days 04:18:35,361115.0
3073778,413971799,C1513126,CN584234,2016-10-05 17:11:50,2016-10-12 21:07:13,7 days 03:55:23,618923.0
3073780,413971724,C1513126,CN584234,2016-10-22 00:40:39,2016-10-23 09:36:21,1 days 08:55:42,118542.0
3073782,413971718,C1513126,CN584234,2016-02-19 00:17:38,2016-03-01 12:09:54,11 days 11:52:16,993136.0
3073791,413971101,C1513126,CN584234,2016-10-26 05:30:06,2016-11-19 23:48:14,24 days 18:18:08,2139488.0
3073792,413971101,C1513126,CN584234,2016-08-30 04:18:13,2016-09-07 03:34:44,7 days 23:16:31,688591.0
3073793,413971088,C1513126,CN584234,2016-04-06 03:24:36,2016-04-07 17:59:41,1 days 14:35:05,138905.0
3073794,413971082,C1513126,CN584234,2016-10-13 04:16:34,2016-10-19 14:53:51,6 days 10:37:17,556637.0
3073795,413970957,C1513126,CN584234,2016-02-03 22:49:24,2016-07-13 13:30:31,160 days 14:41:07,13876867.0
3073796,413970950,C1513126,CN584234,2016-07-13 14:38:41,2016-07-20 05:13:22,6 days 14:34:41,570881.0
3073797,413970713,C1513126,CN584234,2016-10-22 15:05:54,2016-10-27 13:36:22,4 days 22:30:28,426628.0
3073798,413970703,C1513126,CN584234,2016-12-20 02:41:27,2016-12-21 09:45:43,1 days 07:04:16,111856.0
3073800,413970629,C1513126,CN584234,2016-11-01 07:18:18,2016-11-20 08:32:30,19 days 01:14:12,1646052.0
3073801,413970118,C1513126,CN584234,2016-09-15 22:00:45,2016-09-22 04:24:00,6 days 06:23:15,541395.0
3073802,413970051,C1513126,CN584234,2016-12-04 07:21:32,2016-12-05 07:38:47,1 days 00:17:15,87435.0
3073803,413970051,C1513126,CN584234,2016-11-01 20:25:49,2016-11-07 06:42:42,5 days 10:16:53,469013.0
3073805,413800655,C1513126,CN584234,2016-01-26 13:42:54,2016-03-02 10:26:52,35 days 20:43:58,3098638.0
3073806,413794693,C1513126,CN584234,2016-06-12 11:45:57,2016-07-15 22:33:32,33 days 10:47:35,2890055.0
3073810,413779029,C1513126,CN584234,2016-11-17 01:40:19,2016-11-19 03:03:10,2 days 01:22:51,177771.0
3073811,413777239,C1513126,CN584234,2016-06-13 20:33:22,2016-07-14 15:03:43,30 days 18:30:21,2658621.0
3073812,413776701,C1513126,CN584234,2016-09-26 09:03:48,2016-09-29 15:47:26,3 days 06:43:38,283418.0
3073813,413776263,C1513126,CN584234,2016-03-25 21:44:56,2016-04-07 09:45:37,12 days 12:00:41,1080041.0
3073814,413775316,C1513126,CN584234,2016-06-30 09:24:34,2016-07-02 04:18:04,1 days 18:53:30,154410.0
3073815,413774415,C1513126,CN584234,2016-07-09 13:33:56,2016-08-03 20:10:12,25 days 06:36:16,2183776.0
3073816,413773775,C1513126,CN584234,2016-08-04 22:38:36,2016-08-24 16:44:06,19 days 18:05:30,1706730.0
3073817,413762879,C1513126,CN584234,2016-10-15 01:52:02,2016-10-26 16:58:51,11 days 15:06:49,1004809.0

In [522]:
dfstats_long_route['min'] = dflong_route[["Start_cell", "End_cell", "epoch_journey_length"]].groupby(["Start_cell", "End_cell"]).agg(min)
dfstats_long_route['max'] = dflong_route[["Start_cell", "End_cell", "epoch_journey_length"]].groupby(["Start_cell", "End_cell"]).agg(max)
dfstats_long_route['sum'] = dflong_route[["Start_cell", "End_cell", "epoch_journey_length"]].groupby(["Start_cell", "End_cell"]).agg(sum)
dfstats_long_route['count'] = dflong_route[["Start_cell", "End_cell", "epoch_journey_length"]].groupby(["Start_cell", "End_cell"]).agg('count')
dfstats_long_route['mean'] = dflong_route[["Start_cell", "End_cell", "epoch_journey_length"]].groupby(["Start_cell", "End_cell"]).agg('mean')
dfstats_long_route

                     epoch_journey_length        min         max          sum  \
Start_cell End_cell
AR530010   AR502580              152624.0   152624.0   8919597.0  219628359.0
           BR502101               79977.0    86975.0   2752287.0  115561937.0
           ES506100              891902.0   891902.0   3728965.0  347913126.0
           FR574330             1181916.0  1181916.0   4847056.0  455966241.0
           UY500041                 264.0    86581.0  28944193.0   88382384.0
AR530080   UY500041                   2.0    89796.0   1344264.0   15230737.0
AU5004P1   AU5299P0               32562.0    86528.0    885363.0    7373896.0
AU5052P0   C1511421              940835.0   940835.0   1857708.0  997991532.0
           C1511742                   2.0   155390.0    902751.0    1366144.0
           C1513519              787175.0   787175.0   2258856.0  272447842.0
           ID5344B2                   2.0    97216.0    357762.0     770964.0
AU5058P0   AU5066P0               15209.0    88073.0    837279.0    3401280.0
           C1511421              728571.0   728571.0   1651869.0  307909689.0
AU5066P0   AU5058P0               13116.0   175736.0  13366217.0   20689831.0
AU5068P1   ID500044                   6.0        NaN         NaN          NaN
AU5073P2   GB503713                   5.0   128975.0    212438.0     542146.0
AU5111X4   AU5230P0                   2.0        NaN         NaN          NaN
AU5113P0   SG5C4043              405792.0   405792.0   3579235.0  294850749.0
AU5137X8   AU5113P0              238683.0   238683.0   1009462.0   78292368.0
           AU5144P0               80098.0    88307.0    412490.0   37004874.0
AU5144P0   AU5137X8               80556.0    86435.0    782636.0   70143488.0
           AU5163P1               33104.0   106190.0    293183.0    1397226.0
           AU5164P1               24039.0    93846.0   1490790.0    2876599.0
           AU5193P0               75125.0    86503.0    350624.0   81321164.0
AU5154P0   AU5237X8                   2.0   335447.0   2968105.0    6296970.0
AU5163P1   AU5144P0               34190.0   670637.0    670637.0     670637.0
AU5164P1   AU5144P0               23755.0    90183.0    176304.0     799744.0
AU5193P0   AU5144P0               78702.0    86402.0    394471.0  111777169.0
           AU5198P0                8908.0    87401.0   1103883.0   15442056.0
AU5198P0   AU5193P0                8159.0    88561.0   3484281.0    8325245.0
...                                   ...        ...         ...          ...
VE500105   C1513519                   2.0        NaN         NaN          NaN
           C1513949                   5.0        NaN         NaN          NaN
           C1513981                  18.0        NaN         NaN          NaN
           VE501302               22619.0    88835.0    809121.0    3387574.0
VE500106   MX505113                   7.0        NaN         NaN          NaN
           PH5SBH40                   6.0        NaN         NaN          NaN
           VE500503                   3.0   208066.0   1390937.0    1599003.0
           VE500515                   3.0        NaN         NaN          NaN
           VE501302               24515.0    88490.0    836783.0    3627043.0
VE500319   GB52020B                   3.0        NaN         NaN          NaN
VE500406   CN584225                   2.0        NaN         NaN          NaN
VE500503   VE500106                   4.0        NaN         NaN          NaN
VE500515   VE500106                   2.0        NaN         NaN          NaN
VE501302   VE500106               23556.0    96091.0    626348.0    3340519.0
VN5DT001   C1515379              145811.0   145811.0   2916233.0   82056839.0
           SG5C4043              102718.0   102718.0  14149804.0  229653945.0
VN5DT003   C1515379              158259.0   158259.0   4464310.0  103665696.0
           SG5C4043              108099.0   108099.0   7174060.0  196560227.0
           TH500156                 939.0   111004.0   1709064.0   52916567.0
VN5DT004   SG5C4043              125374.0   125374.0   8183275.0  194130883.0
VN5SDI01   SG5C4043               98279.0    98279.0  10044524.0  135494688.0
ZA500050   UA53404C                   4.0        NaN         NaN          NaN
ZA500120   ZA500050                4945.0    87271.0  13647935.0   85619499.0
ZA500125   ZA500160               70371.0    86631.0   3602824.0   53576256.0
ZA500160   BH51501B                   4.0        NaN         NaN          NaN
           SG5C4039              901084.0   901084.0   8336590.0  532660631.0
           ZA500050               49117.0   125188.0  14567113.0  172027893.0
           ZA500120               62905.0    86416.0   1127777.0   45585747.0
           ZA500170               21163.0    88325.0  15067061.0  131573707.0
ZA500170   SG5C4039             1191623.0  1191623.0   3896312.0  531238821.0

                     count          mean
Start_cell End_cell
AR530010   AR502580  317.0  6.928339e+05
           BR502101  336.0  3.439343e+05
           ES506100  238.0  1.461820e+06
           FR574330  272.0  1.676346e+06
           UY500041  163.0  5.422232e+05
AR530080   UY500041   37.0  4.116415e+05
AU5004P1   AU5299P0   58.0  1.271361e+05
AU5052P0   C1511421  805.0  1.239741e+06
           C1511742    3.0  4.553813e+05
           C1513519  263.0  1.035923e+06
           ID5344B2    4.0  1.927410e+05
AU5058P0   AU5066P0   16.0  2.125800e+05
           C1511421  245.0  1.256774e+06
AU5066P0   AU5058P0    8.0  2.586229e+06
AU5068P1   ID500044    NaN           NaN
AU5073P2   GB503713    3.0  1.807153e+05
AU5111X4   AU5230P0    NaN           NaN
AU5113P0   SG5C4043  463.0  6.368267e+05
AU5137X8   AU5113P0  217.0  3.607943e+05
           AU5144P0  250.0  1.480195e+05
AU5144P0   AU5137X8  459.0  1.528181e+05
           AU5163P1    8.0  1.746532e+05
           AU5164P1   12.0  2.397166e+05
           AU5193P0  667.0  1.219208e+05
AU5154P0   AU5237X8    4.0  1.574242e+06
AU5163P1   AU5144P0    1.0  6.706370e+05
AU5164P1   AU5144P0    7.0  1.142491e+05
AU5193P0   AU5144P0  884.0  1.264448e+05
           AU5198P0   76.0  2.031849e+05
AU5198P0   AU5193P0   11.0  7.568405e+05
...                    ...           ...
VE500105   C1513519    NaN           NaN
           C1513949    NaN           NaN
           C1513981    NaN           NaN
           VE501302   20.0  1.693787e+05
VE500106   MX505113    NaN           NaN
           PH5SBH40    NaN           NaN
           VE500503    2.0  7.995015e+05
           VE500515    NaN           NaN
           VE501302   23.0  1.576975e+05
VE500319   GB52020B    NaN           NaN
VE500406   CN584225    NaN           NaN
VE500503   VE500106    NaN           NaN
VE500515   VE500106    NaN           NaN
VE501302   VE500106   15.0  2.227013e+05
VN5DT001   C1515379  253.0  3.243353e+05
           SG5C4043  441.0  5.207572e+05
VN5DT003   C1515379  366.0  2.832396e+05
           SG5C4043  716.0  2.745255e+05
           TH500156  328.0  1.613310e+05
VN5DT004   SG5C4043  429.0  4.525195e+05
VN5SDI01   SG5C4043  368.0  3.681921e+05
ZA500050   UA53404C    NaN           NaN
ZA500120   ZA500050  205.0  4.176561e+05
ZA500125   ZA500160  203.0  2.639224e+05
ZA500160   BH51501B    NaN           NaN
           SG5C4039  369.0  1.443525e+06
           ZA500050  243.0  7.079337e+05
           ZA500120  206.0  2.212900e+05
           ZA500170  207.0  6.356218e+05
ZA500170   SG5C4039  323.0  1.644702e+06

[4142 rows x 6 columns]

In [507]:
#df.loc[df['Start_cell'] == 'AR530010'].sort_values('epoch_journey_length', ascending=False)